### ISSUE TITLE
Slides formatting issue

### ISSUE THREAD

**Issue by arnonuem** [Zulko/eagle.js#11]
Slides are not formatted correctly when 'eagle-recipes' is not included in 'slideshows.js'.
The height of 100% seems to have gone which makes the slide background looking ugly.

**Comment by Zulko** [comment]
If you want to make your own themes, they should import [base.scss](https://github.com/Zulko/eagle.js/blob/master/src/themes/_base.scss) as a base, which defines the most important layout features.

The idea is that the base theme defines as little styles as possible so that you are really free of doing what you want in your own themes.

**Comment by arnonuem** [comment]
Could you please run a test with the following setup and evaluate the result to see that everything is like you expect it?

- clone https://github.com/Zulko/eaglejs-demo.git
- edit slideshows.js to just contain ".../FirstSlideshow"
  - remove `require('./introducing-eagle/IntroducingEagle'), require('./eagle-recipes/EagleRecipes'), require('./themes-slideshow/ThemesSlideshow'),`
- run and check the background setting of the first slideshow

**Comment by yaodingyd** [comment]
@arnonuem I have run your steps and cannot reproduce your issue. If your issue persists, please open an issue in eaglejs-demo and attach an screenshot. Thanks.
