### ISSUE TITLE
swipe support for mobile

### ISSUE THREAD

**Issue by dcsan** [Zulko/eagle.js#21]
Hi! Looks like a great project, but when I opened a deck on my phone, it doesn't work. it suggests i use ctrl-arrow for navigation.

is there an example of using hammerJS or other tap/touch events to swipe for mobile?

**Comment by Zulko** [comment]
It is not supposed to support swipe, you must click or touch on the left or right of the screen to go to the next/previous slide. Does it work when you touch the right/left borders of the screen on your phone ?

**Comment by dcsan** [comment]
oh ok. I didn't think to try that, like most users. 

revealJS works really nicely on mobile so I guess we should just use that if this isn't intended to support mobile type UI interactions?

**Comment by Zulko** [comment]
If your presentation can be done using Reveal, you should use Reveal, it is simpler deploy/edit/etc.

You can also try to get HammerJS' swipe to work with Eagle it shouldnt be very difficult (when i first tried I had issues with some browsers though).

**Comment by gpolitog** [comment]
+1 to add swipe support (maybe with another library if you already had issues with hammer), because swiping is what comes to the mind of a mobile user, who may not even think/try to tap left & right sides of the slide.

revealJS may be very popular, but Eagle is awsome because is Vue-powered.  You can use Eagle to create quizes, and send results to backend.  That wouldn't be easy with revealJS.

please consider adding swipe support :)

**Comment by dcsan** [comment]
right. we were hoping to use the system for flashcards at least, and a fun quiz would be better :)

**Comment by yaodingyd** [comment]
@Zulko  I'm thinking for all non-core functionalities, we create examples in demo repo to show users  how to integrate with third party libraries. If you are OK with this I'll get started with it. There are some examples that appeared in issues before: permalink  and timer.

**Comment by yaodingyd** [comment]
Update in project Readme [here](https://github.com/Zulko/eagle.js#mobile-support).
