### ISSUE TITLE
vue-cli template

### ISSUE THREAD

**Issue by ghost** [Zulko/eagle.js#7]
It'd be nice to have a vue-cli template for this.

**Comment by elpete** [comment]
I wrote one up here: https://github.com/elpete/eaglejs-template

I'd be happy to transfer it.

**Comment by Zulko** [comment]
@elpete looks very cool. I see that initially you had all slideshows, and you simplified to just one slideshow in Home.vue.

I think a middle solution would be to keep the structure of my example slides (in particular because it implements the "slideshow gallery" which is very practical) but keeping only the "my first slideshow" example, as it allows to start writing directly. I think it's a good thing to encourage "one folder per slideshow" in the same project, it makes it easier to reuse and trasfer presentations.

**Comment by elpete** [comment]
I've made those changes.  Let me know what you think.  Again, we can keep it under my namespace or transfer it.  Either way.

**Comment by Zulko** [comment]
Cool, thanks. I think I'll create an eagle.js organization to host the library, the cli template, the demo, etc. Would you be interested in becoming a maintainer ?

**Comment by elpete** [comment]
Sure thing. 😄

**Comment by angeliski** [comment]
Hey @Zulko , you need help to create the organization? 
I would be happy to help :)

**Comment by Zulko** [comment]
No I was just swamped and I wanted to try my hand with organizations on a new project first.  Will certainly do the change soon.

**Comment by yaodingyd** [comment]
added to readme
